project_id = "sbvuvpfeooqotscyonhz"

[functions.invite-users]
verify_jwt = false

[functions.parse-cv]
verify_jwt = false

[functions.send-notification-email]
verify_jwt = false

[functions.create-xendit-invoice]
verify_jwt = false

[functions.xendit-webhook]
verify_jwt = false

[functions.request-quote]
verify_jwt = false

[functions.generate-cv]
verify_jwt = false
